BOARD = arduino:avr:mega:cpu=atmega2560

LIBRARIES := ./libraries

include ../Arduino.mk

# /home/adumont/opt/arduino-1.8.6/hardware/tools/avr/bin/avrdude -C/home/adumont/opt/arduino-1.8.6/hardware/tools/avr/etc/avrdude.conf -v -patmega2560 -cwiring -P/dev/ttyUSB1 -b115200 -D -Uflash:w:/tmp/arduino_build_612380/mega.ino.hex:i 

